version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    volumes:
      - ./rabbitmq/:/etc/rabbitmq/
    ports:
      - '1883:1883'
      - '5672:5672'
      - '15672:15672'
    environment:
      hostname: 'rabbitmq'
      name: 'rmq'
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes: 
      - database:/var/lib/postgresql/data

  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1

  server:
    build: server
    volumes:
      - ./server:/app
    ports:
      - 8080:8080

volumes:
  database:
    driver: local